package com.togethertrip.notification.notification.service

object NotificationEventContract {
    const val TRIP_PARTICIPANTS_ADDED = "TRIP_PARTICIPANTS_ADDED"
    const val TRIP_PARTICIPANT_JOINED = "TRIP_PARTICIPANT_JOINED"
    const val TRIP_PARTICIPANT_REMOVED = "TRIP_PARTICIPANT_REMOVED"
    const val POST_CREATED = "POST_CREATED"
    const val EXPENSE_POST_CREATED = "EXPENSE_POST_CREATED"
    const val POST_COMMENT_CREATED = "POST_COMMENT_CREATED"
    const val SETTLEMENT_CONFIRMED = "SETTLEMENT_CONFIRMED"
    const val SETTLEMENT_TRANSFER_CONFIRMED_BY_SENDER = "SETTLEMENT_TRANSFER_CONFIRMED_BY_SENDER"
    const val SETTLEMENT_TRANSFER_COMPLETED = "SETTLEMENT_TRANSFER_COMPLETED"

    const val AGGREGATE_TRIP = "TRIP"
    const val AGGREGATE_POST = "POST"
    const val AGGREGATE_SETTLEMENT = "SETTLEMENT"
}
