spring:
  application:
    name: notification

  profiles:
    default: local

server:
  port: 8082

notification:
  sqs:
    queue-url: ${NOTIFICATION_QUEUE_URL:}
    region: ${AWS_REGION:ap-northeast-2}
    enabled: ${NOTIFICATION_SQS_ENABLED:true}
    max-messages: ${NOTIFICATION_SQS_MAX_MESSAGES:10}
    wait-time: ${NOTIFICATION_SQS_WAIT_TIME:PT10S}
    visibility-timeout: ${NOTIFICATION_SQS_VISIBILITY_TIMEOUT:PT30S}
    fixed-delay: ${NOTIFICATION_SQS_FIXED_DELAY:PT3S}
