create table notifications (
    id bigint generated by default as identity primary key,
    source_event_id bigint not null,
    recipient_user_id bigint not null,
    event_type varchar(50) not null,
    aggregate_type varchar(50) not null,
    aggregate_id bigint not null,
    payload_snapshot text not null,
    occurred_at timestamp with time zone,
    read_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    deleted_at timestamp with time zone,
    constraint uk_notifications_source_event_recipient unique (source_event_id, recipient_user_id)
);
