alter table notifications add column title varchar(120);
alter table notifications add column body varchar(500);
alter table notifications add column deeplink varchar(255);

update notifications
set title = '새 알림이 도착했습니다',
    body = event_type || ' 이벤트가 도착했습니다.'
where title is null
   or body is null;

alter table notifications alter column title set not null;
alter table notifications alter column body set not null;

create table push_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    token varchar(1024) not null,
    platform varchar(20) not null,
    device_id varchar(120),
    active boolean not null,
    last_registered_at timestamp with time zone not null,
    invalidated_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    deleted_at timestamp with time zone,
    constraint uk_push_tokens_token unique (token)
);

create index idx_push_tokens_user_active
    on push_tokens (user_id, active);

create table push_delivery_attempts (
    id bigint generated by default as identity primary key,
    notification_id bigint not null,
    push_token_id bigint not null,
    status varchar(30) not null,
    provider_message_id varchar(200),
    failure_reason varchar(200),
    attempted_at timestamp with time zone not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    deleted_at timestamp with time zone
);

create index idx_push_delivery_attempts_notification
    on push_delivery_attempts (notification_id);

create index idx_push_delivery_attempts_push_token
    on push_delivery_attempts (push_token_id);
