create table deleted_accounts (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    source_event_id bigint not null,
    deleted_at timestamp with time zone not null,
    constraint uk_deleted_accounts_user unique (user_id),
    constraint uk_deleted_accounts_source_event unique (source_event_id)
);

