name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-test:
    name: Build Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: together_trip_test
          POSTGRES_USER: together_trip
          POSTGRES_PASSWORD: together_trip
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U together_trip -d together_trip_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Compile
        run: ./gradlew compileKotlin

      - name: Test
        run: ./gradlew test

      - name: Package
        run: ./gradlew bootJar